# Generated by Django 2.2.2 on 2019-06-12 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartesHearthstone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True)),
                ('imageCarte', models.CharField(default='', max_length=500)),
                ('dateToBD', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
