# Generated by Django 2.2.2 on 2019-06-12 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HearthstoneApp', '0005_auto_20190612_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('dateDeNaissance', models.DateField(default=datetime.datetime.now)),
                ('pseudo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=50)),
                ('contenu', models.CharField(default='', max_length=10000)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HearthstoneApp.Auteur')),
            ],
        ),
    ]
