# Generated by Django 2.2.2 on 2019-06-12 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HearthstoneApp', '0006_article_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
