# Generated by Django 2.2.2 on 2019-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HearthstoneApp', '0007_auto_20190612_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(default=''),
        ),
    ]
